### ISSUE TITLE
드래그로 지도 확대 및 축소 시 지연 현상

### ISSUE THREAD

**Issue by nuyh99** [woowacourse-teams/2023-map-befine#217]
### 🐞버그 설명

지도의 오른쪽에 있는 확대, 축소 기능은 바로 이동돼서 빠릅니다.
하지만 스크롤로 확대 및 축소를 하면 매우 느려요ㅠㅠ

### 🌏 버그 발생 환경

OS: Mac OS
브라우저: 사파리

### ✅ 버그 재현 방법

//given
지도 화면

//when
마우스 스크롤

//then
확대 및 축소가 가능하지만 체감상 매우 느리다

### ⏰ 추정 시간

제가 팀이 아니라서 잘 모르겠습니다ㅠ

**Comment by cpot5620** [comment]
감사합니다.
@afds4567

**Comment by afds4567** [comment]
Vector맵 적용으로 해결했습니다~
