### ISSUE TITLE
핀 추가가 안됩니다

### ISSUE THREAD

**Issue by donghae-kim** [woowacourse-teams/2023-map-befine#219]
### 🐞버그 설명

![image](https://github.com/woowacourse-teams/2023-map-befine/assets/86547109/148a85be-4311-44e8-9ba5-0d68468b7de5)

이름 길게 입력했더니 추가버튼은 눌리는데 실제로 안되는것같아요

### 📄 버그 로그

```shell
.
```

### 🌏 버그 발생 환경

.

### ✅ 버그 재현 방법

제목 : 건대호수건대호수건대호수건대호수건대호수건대호수건대호수건대호수건대호수건대호수건대호수건대호수건대호수건대호수건대호수건대호수건대호수건대호수건대호수건대호수건대호수건대호수건대호수건대호수건대호수건대호수건대호수건대호수

설명 : 건대호수건대호수건대호수건대호수건대호수건대호수건대호수건대호수건대호수건대호수건대호수건대호수건대호수건대호수건대호수건대호수건대호수건대호수건대호수건대호수건대호수건대호수건대호수건대호수건대호수건대호수건대호수건대호수

### 📎 참고 자료

.

### ⏰ 추정 시간

.

**Comment by cpot5620** [comment]
장소 이름에 대한 제약 조건을 달아두었는데, 프론트 분들이 일을 안 하네요 ...
@semnil5202
