### ISSUE TITLE
주소 선택 창이 하나만 뜨면 좋겠어요

### ISSUE THREAD

**Issue by solo5star** [woowacourse-teams/2023-map-befine#220]
### 🐞버그 설명

주소를 선택하는 창을 계속 클릭하면 많이 켜지는데 하나만 켜졌으면 좋겠습니다.

![image](https://github.com/woowacourse-teams/2023-map-befine/assets/20203944/8cccac54-c1d4-47d9-9ec8-db5a8b44dac0)

### 📄 버그 로그

```shell
.
```

### 🌏 버그 발생 환경

Chrome | 115.0.5790.170 (공식 빌드) (64비트) (cohort: 115_170 Stable Control(A))
개정 | cc0d30c2ca5577520c8646671513241faa0bc105-refs/branch-heads/5790@{#1923}
OS | Windows 11 Version 22H2 (Build 22621.1992)
JavaScript | V8 11.5.150.22
사용자 에이전트 | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36

### ✅ 버그 재현 방법

![image](https://github.com/woowacourse-teams/2023-map-befine/assets/20203944/34f5c2d7-7815-4adc-8ced-54489d35f239)

이 친구를 계속 눌러요

### 📎 참고 자료

.

### ⏰ 추정 시간

.

**Comment by cpot5620** [comment]
진짜 프론트가 일 안 하네요
@afds4567

**Comment by afds4567** [comment]
성격이 급하시네요

**Comment by afds4567** [comment]
@solo5star 수정했습니다~

**Comment by solo5star** [comment]
고마워요 아이크

**Comment by solo5star** [comment]
고마워요 아이크

**Comment by solo5star** [comment]
고마워요 아이크
