### ISSUE TITLE
지도 스크롤 바가 수정되면 좋겠어요

### ISSUE THREAD

**Issue by cookienc** [woowacourse-teams/2023-map-befine#221]
### 🐞버그 설명

<img width="1436" alt="image" src="https://github.com/woowacourse-teams/2023-map-befine/assets/83010167/1a2d03fe-fc39-48de-828a-79a9738e0750">
오른쪽 바가 더 내려갈 것 같이 되어있는데 안 내려가네요.
현재 범위가 최소라면 바를 수정해야될것 같습니다!

### 🌏 버그 발생 환경

맥북에서 실행했습니다.

### ⏰ 추정 시간

10분컷?

**Comment by cpot5620** [comment]
@afds4567 
하.. 프론트 진짜 ㅋㅋ
