### ISSUE TITLE
핀 추가 버튼 후 취소 시 어딘가로 지도 위치 이동

### ISSUE THREAD

**Issue by hyena0608** [woowacourse-teams/2023-map-befine#222]
### 🐞버그 설명

핀 추가 버튼을 누른다. -> 지도를 움직인다. -> 취소하기 버튼을 누른다.  -> 지도 위치가 어딘가로(핀 위치) 리셋됩니다.

이게 정책이면 버그라고 할 수는 없다고 생각하지만 
핀 추가 버튼을 누른 후 다른 곳을 보다가 취소 버튼을 누르면 이전 위치로 돌아가서 속상했습니다.

### 📄 버그 로그

```shell
x
```

### 🌏 버그 발생 환경

macOS, ***Arc***

### ✅ 버그 재현 방법

<img width="1912" alt="image" src="https://github.com/woowacourse-teams/2023-map-befine/assets/82203978/75a2a722-9982-4c0d-9b01-e9336d123989">
<img width="1912" alt="스크린샷 2023-08-07 오후 1 57 33" src="https://github.com/woowacourse-teams/2023-map-befine/assets/82203978/4dabf8dc-41c9-4bb0-95c4-f1eae765bd86">
<img width="1912" alt="image" src="https://github.com/woowacourse-teams/2023-map-befine/assets/82203978/b732aaa8-7450-4fd0-97ad-87853315f637">

### 📎 참고 자료

x

### ⏰ 추정 시간

x

**Comment by semnil5202** [comment]
유저가 핀 추가하기 위해 본 마지막 위치를 고정해볼 필요도 있겠군요. 감사합니다
