### ISSUE TITLE
병합하고 난 이후 화면 문제

### ISSUE THREAD

**Issue by donghae-kim** [woowacourse-teams/2023-map-befine#223]
### 🐞버그 설명

![image](https://github.com/woowacourse-teams/2023-map-befine/assets/86547109/9736943d-b763-4885-8c21-002fa38e027b)

모든 토픽 병합하고 난 이후에 북한과 중국을 보여줘요..

### 📄 버그 로그

```shell
.
```

### 🌏 버그 발생 환경

.

### ✅ 버그 재현 방법

.

### 📎 참고 자료

.

### ⏰ 추정 시간

.

**Comment by semnil5202** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ아이크 성향 확인했습니다

**Comment by afds4567** [comment]
이웃을 우리가 정할 수는 없으니 어울려살아야죠
