### ISSUE TITLE
줄 바뀜이 반영되면 좋겠어요

### ISSUE THREAD

**Issue by solo5star** [woowacourse-teams/2023-map-befine#224]
### 🐞버그 설명

![image](https://github.com/woowacourse-teams/2023-map-befine/assets/20203944/106f4827-aafa-4869-8aa1-4a7d452f0d02)

---

![image](https://github.com/woowacourse-teams/2023-map-befine/assets/20203944/666277ea-8e69-433b-afbf-3737954becce)

줄 바꿈을 넣었는데 실제론 줄 바꿈이 반영이 안돼요

### 📄 버그 로그

```shell
.
```

### 🌏 버그 발생 환경

Chrome | 115.0.5790.170 (공식 빌드) (64비트) (cohort: 115_170 Stable Control(A))
개정 | cc0d30c2ca5577520c8646671513241faa0bc105-refs/branch-heads/5790@{#1923}
OS | Windows 11 Version 22H2 (Build 22621.1992)
JavaScript | V8 11.5.150.22
사용자 에이전트 | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36

### ✅ 버그 재현 방법

핀 세부 정보에 들어가서 장소 설명을 편집합니다

### 📎 참고 자료

.

### ⏰ 추정 시간

.

**Comment by semnil5202** [comment]
오호,, 이건 정말 예상치 못했군요 감사합니다.

**Comment by afds4567** [comment]
해결이요~
