### ISSUE TITLE
핀 추가 입력란 validate

### ISSUE THREAD

**Issue by green-kong** [woowacourse-teams/2023-map-befine#225]
### 🐞버그 설명

그 입력란에 빨간 점이 있어서 필수 입력처럼 느껴지는데 입력을 안해도 페이지는 넘어가고,
실제로 반영은 안되네용

### 📄 버그 로그

```shell
.
```

### 🌏 버그 발생 환경

.

### ✅ 버그 재현 방법

.

### 📎 참고 자료

<img width="387" alt="image" src="https://github.com/woowacourse-teams/2023-map-befine/assets/96301958/c0b7ff9e-5df8-46ed-b0b2-e8e2cc35f20d">

### ⏰ 추정 시간

.

**Comment by semnil5202** [comment]
validation 기능 추가 중에 있습니다. 감사합니다!
