### ISSUE TITLE
[버그] 레이아웃 관련 및 장소 제목 길이 관련 이슈

### ISSUE THREAD

**Issue by gyeongza** [woowacourse-teams/2023-map-befine#227]
### 🐞버그 설명

잘 봤습니다.. 나중에 데이트할 때나 친구들 놀러올 때 쓰면 좋을 것 같네요 👍

### 1. 기본적인 레이아웃 관련

<img width="381" alt="스크린샷 2023-08-07 오후 1 57 59" src="https://github.com/woowacourse-teams/2023-map-befine/assets/62369936/9f0be6c4-3de9-4d69-a52d-3aeaae2060e9">

- 주제와 토픽 추가하기 버튼이 겹쳐서 실수로 토픽을 누르는 경우가 있었습니다.

<img width="405" alt="스크린샷 2023-08-07 오후 2 00 38" src="https://github.com/woowacourse-teams/2023-map-befine/assets/62369936/7588a4bf-7118-42b8-9cb0-2de0a5e2699b">

- 수정하기가 깨져용

### 🌏 버그 발생 환경

OS: mac OS
브라우저: 크롬

### ⏰ 추정 시간

잘 모르겠습니다.

**Comment by semnil5202** [comment]
오우 소중한 피드백 감사합니다!
