### ISSUE TITLE
사진이 너무 혐오스러워요.

### ISSUE THREAD

**Issue by geuntaek1013** [woowacourse-teams/2023-map-befine#228]
### 🐞버그 설명

<img width="395" alt="스크린샷 2023-08-07 오후 2 02 53" src="https://github.com/woowacourse-teams/2023-map-befine/assets/95906910/52d6bb75-bc5e-4a15-b3e0-333acdbd35f9">

밤에 불 끄고 보면은 놀랠 것 같아요.

### 📄 버그 로그

```shell
.
```

### 🌏 버그 발생 환경

macOS

### ✅ 버그 재현 방법

랜딩 페이지에 들어간다 -> 기능을 살펴본다 -> 사진이 나온다

### 📎 참고 자료

.

### ⏰ 추정 시간

.

**Comment by semnil5202** [comment]
해당 인원의 용모를 수정해보도록 하겠습니다. 감사합니다.
