### ISSUE TITLE
핀 추가 시 정보 입력 안하고 추가하기 선택하면 토픽화면으로 나가짐

### ISSUE THREAD

**Issue by hum02** [woowacourse-teams/2023-map-befine#229]
### 🐞버그 설명

의도된 동작인지 모르겠으나 핀 추가 시 정보 입력 안하고 추가하기 선택하면 토픽화면으로 나가져요
필수정보를 입력하지 않았습니다! 같은 alert가 나오는 건 어떤지요

### 🌏 버그 발생 환경

Mac os, 크롬 브라우저

### ✅ 버그 재현 방법

아래와 같이 핀 추가할 때
<img width="1040" alt="image" src="https://github.com/woowacourse-teams/2023-map-befine/assets/96762301/92c5edcc-f8b2-49d7-90a7-de5043382cc9">

정보 입력 덜하고 추가하기 누르면 아래처럼 토픽 화면으로 넘어가지는 상황입니다
<img width="1193" alt="image" src="https://github.com/woowacourse-teams/2023-map-befine/assets/96762301/62e5282f-0e86-4404-961d-f341f5798fd1">

### ⏰ 추정 시간

2시간

**Comment by semnil5202** [comment]
validation 기능 추가 중에 있습니다. 감사합니다!
