### ISSUE TITLE
제안드립니다.

### ISSUE THREAD

**Issue by jeongwusi** [woowacourse-teams/2023-map-befine#230]
### 🐞버그 설명

- 생성하기를 눌렀을 때 필수 항목을 입력해 달라는 경고창이나 토스트 메시지 등이 있으면 좋겠습니다.
- 깡통 버튼의 경우 준비중이라는 메시지가 있으면 좋겠습니다.
- 모바일 환경에서 지원 부탁드립니다.
- 추가하기를 누르면 뒤로가기가 됩니다.

https://github.com/woowacourse-teams/2023-map-befine/assets/122500517/9250b129-9324-4eb4-97b0-9c7e84640296

### 🌏 버그 발생 환경

macOS, iOS

### ⏰ 추정 시간

8월 7일 약 14:00

**Comment by semnil5202** [comment]
validation 기능 추가 중에 있습니다. 감사합니다!
