### ISSUE TITLE
스크롤 빠르게 사용 시 지도 생성 멈춤 현상

### ISSUE THREAD

**Issue by geuntaek1013** [woowacourse-teams/2023-map-befine#231]
### 🐞버그 설명

지도 확대나 축소를 할려고 스크롤을 빠르게 하면 지도 생성이 멈춰버립니다.

### 📄 버그 로그

```shell
-
```

### 🌏 버그 발생 환경

macOS

### ✅ 버그 재현 방법

.

### 📎 참고 자료

<img width="700" alt="스크린샷 2023-08-07 오후 2 12 40" src="https://github.com/woowacourse-teams/2023-map-befine/assets/95906910/dc04895c-e3d3-4408-98c2-4f62399990a8">

- 영상이 안 올라가서 스크린 샷으로 대체합니다.

### ⏰ 추정 시간

.

**Comment by semnil5202** [comment]
TMAP 고유의 문제로 확인됩니다.

https://www.tmap.co.kr/my_tmap/my_map_tip/map_tip.do

사용자 스크롤 이벤트를 제한하기 등 여러 방안 모색중에 있습니다. 감사합니다

**Comment by afds4567** [comment]
vector맵 적용해서 해결했습니다~
