### ISSUE TITLE
불필요한 스크롤 바가 나타나는 문제

### ISSUE THREAD

**Issue by solo5star** [woowacourse-teams/2023-map-befine#232]
### 🐞버그 설명

![image](https://github.com/woowacourse-teams/2023-map-befine/assets/20203944/f3241a0f-aec7-4ba4-b1a2-542b857fa709)

화면 전체에 스크롤 바가 생깁니다.

### 📄 버그 로그

```shell
.
```

### 🌏 버그 발생 환경

Chrome | 115.0.5790.170 (공식 빌드) (64비트) (cohort: 115_170 Stable Control(A))
개정 | cc0d30c2ca5577520c8646671513241faa0bc105-refs/branch-heads/5790@{#1923}
OS | Windows 11 Version 22H2 (Build 22621.1992)
JavaScript | V8 11.5.150.22
사용자 에이전트 | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36

### ✅ 버그 재현 방법

화면 크기를 조금만 줄여도 창 자체에 스크롤 바가 생깁니다.

### 📎 참고 자료

.

### ⏰ 추정 시간

.

**Comment by GC-Park** [comment]
빠르게 수정하도록 하겠습니다! 감사합니다!
