### ISSUE TITLE
없는 pinDetail 아이디 입력하면 터져요

### ISSUE THREAD

**Issue by cookienc** [woowacourse-teams/2023-map-befine#234]
### 🐞버그 설명

<img width="911" alt="image" src="https://github.com/woowacourse-teams/2023-map-befine/assets/83010167/9b73ebc0-e6f3-4c39-8867-d1eb61f5301b">
<img width="989" alt="image" src="https://github.com/woowacourse-teams/2023-map-befine/assets/83010167/c33695ce-2b6d-4257-a23b-855d022b09eb">
topic도 그러네요

### 🌏 버그 발생 환경

맥북

### ⏰ 추정 시간

1~2시간

**Comment by junpakPark** [comment]
땡큐땡큐
