### ISSUE TITLE
[ALL] 스프린트4 방향성 및 일정 추정

### ISSUE THREAD

**Issue by yoondgu** [woowacourse-teams/2023-map-befine#235]
### 📝 설명

3차 데모데이 피드백을 기반으로 스프린트4 방향성을 정하고, 구체적인 일정 추정을 진행한다.
결과물로는 필요한 이슈들을 발행하고 할당한다.

### 🙋🏻 참가 인원

7명

### ⏰ 회의 시간

16:30 ~

### 전체 방향성 관련
데모데이 사용성 관련 피드백(이 서비스에서 무엇을 해야 할지 알기 어려움)을 고려해 이번 스프린트 방향성을 정한다.
4차 데모데이 발표 시 목표를 정한다.
- [x] 랜딩 페이지 vs 어떻게 서비스 사용법을 사용자들에게 제안할 것인지?
    - 준팍 피그마 시안 제안
- [x] 지도 구현을 멈추고, 사이드바에 집중할 것인지?
- [x] 4차 데모데이 목표 정하기
- [x] 운영 서버 배포 시점 정하기

### 인프라 관련 TODO
언제까지, 누가 해결할지 정한다.
- [x] Url rewrite 설정 변경, 관련 명세 수정(fe, be 같이보기 API 코드)
- [x] 프론트 자동배포 이슈 해결 

### 기능 관련 TODO
필요한 기능 보완 및 추가 사항을 확인하고 우선순위를 정한다.
- [x] `기능&UI` 서비스 사용법을 위한 depth 추가 ?
- [x] `기능 보완` 새 API 구현 및 연결 (코멘트에 세부사항 작성함)
- [ ] `기능 보완` 핀 추가 시 세부 주소 입력
- [x] `기능 보완` 버그 리포팅 참고하여 검증 로직 보완
- [x] `새 기능` 권한 추가
- [x] `새 기능` 소셜 로그인
- [ ] `기능 보완` 예외에 맞는 응답 보내고 처리하기

### 정책 관련 TODO
- [x] 핀 위치 전국 허용할 것인지, 잠실 주변으로 제한할 것인지?
- [x] 예외 상태 코드 정리 : 백엔드 코드 다 머지한 후 예외사항 쭉 정리
- [x] 기본 검증 관련 프론트, 백엔드 싱크 맞추기

(회의 안건은 제가 임의로 얘기나온 것들 정리해보았습니다.)

### ⏰ 추정 시간

낙관적 추정: 3시간
비관적 추정: + .... 그래도 오늘 안에 끝내기!!!!

**Comment by yoondgu** [comment]
### 사용성 피드백으로 인한 UI 변경
- 준팍 피그마 시안 UI로 빠르게 변경 후, 사용자 피드백 받기
- 사용자 피드백에 따라 추가 구현 필요한지 판단하기
    - 사용법 가이드가 필요하다는 의견이 대다수이면 -> 사용법을 제공하는 랜딩 페이지 추가
    - 지도에 대한 피드백만 너무 많이 나오면 -> 지도가 주가 되지 않도록 메인 페이지 적용 
    
### UI 변경에 따른 기능 변경 사항
- 토픽 병합 대신, 모아보기 -> 핀 뽑아오기 프로세스로 통일 (토픽 병합 명세 사용 X)
- 모아보기를 위한 API 추가 (장바구니처럼 하고, 한번에 보기 누르면 모아보기 목록에서 삭제)
- 특정 핀에 대해 내 지도에 저장하기 API 추가

**Comment by junpakPark** [comment]
**완성된 API목록**
- 나의 핀 조회
- 나의 지도 조회

**Comment by yoondgu** [comment]
## UI 확정 회의

### 백엔드 참고사항
- 핀 추가 권한이 있는 모든 지도 조회 API가 필요
    - 핀 추가 화면, 핀 상세 화면에서 내 지도 추가하기 기능에서 필요
- 핀 사진 추가 기능은 S3 적용 이후 구현 예정

### 변경 내용 공유
- 메인 화면을 기본 UI로 두고, 지도가 필요한 상황마다(토픽 상세 조회, 모아보기 조회 등) 사이드바-지도 구성의 UI로 변경됨
- 메인 화면에서 항목 별로 3개씩만 보여주어도 될 것 같다.
- 모바일 대응에서는 기존 사이드바 활용 예정

### 적용 예정 사항
- (+) 버튼 클릭하면 여러 옵션이 나오게 할 예정
- (+) 버튼이 뭔지 이해할 수 있게 하기
- 로그인 : 보관함 대신 내 정보 & 로그인
- 권한 : 토픽 생성 시 권한 선택 항목 추가
