### ISSUE TITLE
[BE] 인프라 구조 설계

### ISSUE THREAD

**Issue by yoondgu** [woowacourse-teams/2023-map-befine#4]
## 작업 대상
- [BE] 인프라 기술스택

## 작업 진행 방법
- [x] 유사 프로젝트의 인프라 설계를 조사한다.
- [x] 우리 프로젝트의 특성에 맞게 인프라 설계 다이어그램 초안을 작성한다.
- [x] 여러 선택지 중 적합한 기술을 선택한다.
- [x] 선택한 기술 스택 기반으로 인프라 설계 다이어그램을 완성한다.

**Comment by junpakPark** [comment]
7/26까지 인프라 구축 완료할 것

**Comment by yoondgu** [comment]
![image](https://github.com/woowacourse-teams/2023-map-befine/assets/97426362/bfdd435f-5fb8-499e-80b4-34bbeced73fe)
