### ISSUE TITLE
[BE] 토픽 조회 시 업데이트 일시를 최근에 핀이 추가된 일시로 변경

### ISSUE THREAD

**Issue by yoondgu** [woowacourse-teams/2023-map-befine#400]
### 🛠️ 작업 대상

Topic 관련 클래스들

### ✅ 작업 내용

<img width="348" alt="image" src="https://github.com/woowacourse-teams/2023-map-befine/assets/97426362/95dec695-397b-44b7-9bea-fd27b909b8e8"><br/>
현재 토픽 조회 시 내려주는 업데이트 일시는 Topic 테이블의 updatedAt인데,  
이를 해당 토픽에 가장 최근 핀이 추가된 일시로 변경합니다.  

방법
1. 테이블 구조 없이 빠르게 변경할 수 있는 방법
- 토픽 조회 시, getPins를 통해 가장 최근에 추가된 일시를 찾는다.  
- 단점: 불필요한 쿼리 다수 발생
2. 테이블 구조 변경과 함께 변경할 수 있는 방법
- 토픽에 pinUpdatedAt 컬럼을 추가하고, Pin이 추가될 때마다 이를 업데이트해준다.
- 추후 이벤트 처리 적용 가능해보임
- 단점: 테이블 스키마 변경을 반영하며, 개발 서버 및 운영 서버의 기존 데이터 처리를 고려해야 함

2번 방법이 더 좋아 보이긴 합니다만 의견 부탁드립니당

### ⏰ 추정 시간

비관적 추정: 12시간
낙관적 추정: 5시간

**Comment by junpakPark** [comment]
2번이요!

**Comment by junpakPark** [comment]
금요일까지 힘들다면 1번 우선 진행하고 추후에 2번 가는 것도 좋습니다

**Comment by kpeel5839** [comment]
저도 2번이 좋아보입니다!
