### ISSUE TITLE
[BE] 성능 최적화를 위한 쿼리 카운터 구현

### ISSUE THREAD

**Issue by junpakPark** [woowacourse-teams/2023-map-befine#422]
### 📄 작업 대상

- 인덱스 도입 전 DB 성능 최적화를 위한 API당 쿼리의 갯수를 세어주는 쿼리 카운터 구현

### ✅ 작업 내용

- [ ] PreparedStatement의 다이나믹 프록시 만들기
- [ ] Connection의 다이나믹 프록시 만들기
- [ ] AOP를 이용하여 Connection의 프록시 반환하기
- [ ] AOP 혹은 인터셉터에서 로깅 하기

### 📎 참고 자료

- [API의 쿼리 개수 세기 - (1) 하이버네이트를 이용한 카운팅](https://velog.io/@ohzzi/API%EC%9D%98-%EC%BF%BC%EB%A6%AC-%EA%B0%9C%EC%88%98-%EC%84%B8%EA%B8%B0-1-%ED%95%98%EC%9D%B4%EB%B2%84%EB%84%A4%EC%9D%B4%ED%8A%B8%EB%A5%BC-%EC%9D%B4%EC%9A%A9%ED%95%9C-%EC%B9%B4%EC%9A%B4%ED%8C%85)
- [API의 쿼리 개수 세기 - (2) JDBC, Spring AOP, Dynamic Proxy를 활용한 카운팅](https://velog.io/@ohzzi/API%EC%9D%98-%EC%BF%BC%EB%A6%AC-%EA%B0%9C%EC%88%98-%EC%84%B8%EA%B8%B0-2-JDBC-Spring-AOP-Dynamic-Proxy%EB%A5%BC-%ED%99%9C%EC%9A%A9%ED%95%9C-%EC%B9%B4%EC%9A%B4%ED%8C%85)
- [[kerdy] AOP, ThreadLocal을 사용하여 N+1 detector 만들어보기](https://c-king.tistory.com/entry/N1-detector-%EB%A7%8C%EB%93%A4%EC%96%B4%EB%B3%B4%EA%B8%B0)

### ⏰ 추정 시간

- 비관적 : 4시간
- 낙관적 : 2시간

**Comment by cpot5620** [comment]
**AOP 대신, Filter를 적용하여서 구현할 수 있는 것을 확인하였습니다.**

### 📄 작업 대상

- 인덱스 도입 전 DB 성능 최적화를 위한 API당 쿼리의 갯수를 세어주는 쿼리 카운터 구현

### ✅ 작업 내용

- [ ] API 요청에 대한 쿼리 횟수 측정
- [ ] API 요청에 대한 처리 시간 측정
- [ ] 필터를 통해, 위 구현 사항 로깅

### 📎 참고 자료

### ⏰ 추정 시간

- 비관적 : 4시간
- 낙관적 : 2시간
