### ISSUE TITLE
[BE] 핀 아이콘을 S3에 이관

### ISSUE THREAD

**Issue by yoondgu** [woowacourse-teams/2023-map-befine#549]
### 📄 작업 설명

핀 아이콘을 S3 에 이관한다.

### ✅ 작업 내용

대동붕어빵여지도와 같은 수 많은 핀을 가진 지도에 접속했을 때, 핀 아이콘을 지도에 그려내는 과정에서 velog 에 무수한 요청을 보내 DDOS 로 인식하는 것을 우려하여 핀 아이콘을 s3 로 이관한다. (velog --> s3)

### ⏰ 추정 시간

낙관적 추정시간 - 30분
비관적 추정시간 - 10분

**Comment by kpeel5839** [comment]
충떵!
