### ISSUE TITLE
[All] Ec2 인스턴스 사용방안 

### ISSUE THREAD

**Issue by cpot5620** [woowacourse-teams/2023-map-befine#82]
### 📝 설명

Aws Ec2 인스턴스가 3개 주어지게 됩니다.
해당 인스턴스를 각각 어떻게 사용할 것인지 토의가 필요합니다.

### 🙋🏻 참가 인원

전원

### ⏰ 회의 시간

7월 24일 13:30 ~ 14:00

### ✅ 회의 안건

- 인스턴스 사용 방법

### ⏰ 추정 시간

비관적 추정 시간 : 1시간 30분
낙관적 추정 시간 : 30분

**Comment by yoondgu** [comment]
#4 와 함께 이슈 닫습니다!
