### ISSUE TITLE
[BE] CI/CD 툴 선택

### ISSUE THREAD

**Issue by cpot5620** [woowacourse-teams/2023-map-befine#83]
### 📝 설명

CI/CD에 사용할 툴을 의논해야 합니다.

### 🙋🏻 참가 인원

4명 (쥬니, 준팍, 매튜, 도이)

### ⏰ 회의 시간

7월 24일 14:00 ~ 15:30

### ✅ 회의 안건

- [x] CI 툴
- [x] CD 툴

### ⏰ 추정 시간

비관적 추정 시간 : 3시간
낙관적 추정 시간 : 1시간

**Comment by yoondgu** [comment]
CI - Github Actions
CD - Github Actions self hosted runner 사용
한정된 서버 개수 및 현재 개발 상황을 고려 했을 때,
지금 Jenkins에서만 제공하는 기능들을 사용할 필요가 없기 때문에
비교적 쉽게 적용할 수 있고 인프라 구축에 부담이 덜한 Github Actions 를 사용하기로 결정함.
